kind: Secret
apiVersion: v1
metadata:
  name: postgresql
  labels:
    template: postgresql-ephemeral-template
  annotations:
    template.openshift.io/expose-database_name: '{.data[''database-name'']}'
    template.openshift.io/expose-password: '{.data[''database-password'']}'
    template.openshift.io/expose-username: '{.data[''database-user'']}'
data:
  database-name: c2FtcGxlZGI=
  database-password: c2VjcmV0
  database-user: dXNlcg==
type: Opaque
