kind: Service
apiVersion: v1
metadata:
  name: postgresql
  labels:
    template: postgresql-ephemeral-template
  annotations:
    template.openshift.io/expose-uri: 'postgres://{.spec.clusterIP}:{.spec.ports[?(.name=="postgresql")].port}'
spec:
  ports:
    - name: postgresql
      protocol: TCP
      port: 5432
      targetPort: 5433
  type: ClusterIP
  selector:
    name: postgresql