kind: Deployment
apiVersion: apps/v1
metadata:
  annotations:
    alpha.image.policy.openshift.io/resolve-names: '*'
    app.openshift.io/connects-to: >-
      [{"apiVersion":"apps/v1","kind":"Deployment","name":"troubleshooting-backend"}]
    app.openshift.io/route-disabled: 'false'
    deployment.kubernetes.io/revision: '1'
    image.openshift.io/triggers: >-
      [{"from":{"kind":"ImageStreamTag","name":"troubleshooting-frontend:latest","namespace":"{{ .Release.namespace }}"},"fieldPath":"spec.template.spec.containers[?(@.name==\"troubleshooting-frontend\")].image","pause":"false"}]
    openshift.io/generated-by: OpenShiftWebConsole
  name: troubleshooting-frontend
  labels:
    app: troubleshooting-frontend
    app.kubernetes.io/component: troubleshooting-frontend
    app.kubernetes.io/instance: troubleshooting-frontend
    app.kubernetes.io/name: troubleshooting-frontend
    app.kubernetes.io/part-of: troubleshooting-backend-app
    app.openshift.io/runtime: quarkus
spec:
  replicas: 0
  selector:
    matchLabels:
      app: troubleshooting-frontend
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: troubleshooting-frontend
        deployment: troubleshooting-frontend
      annotations:
        openshift.io/generated-by: OpenShiftWebConsole
    spec:
      containers:
        - name: troubleshooting-frontend
          image: >-
            image-registry.openshift-image-registry.svc:5000/troubleshooting/troubleshooting-frontend@sha256:fab86fba59c0e472a8927164c46ef0999e8e2d44d907050e6a4c1b4e526fea35
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 8443
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
---
kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  annotations:
    openshift.io/image.dockerRepositoryCheck: '2023-11-06T16:51:27Z'
  name: troubleshooting-frontend
  labels:
    app: troubleshooting-frontend
    app.kubernetes.io/component: troubleshooting-frontend
    app.kubernetes.io/instance: troubleshooting-frontend
    app.kubernetes.io/name: troubleshooting-frontend
    app.kubernetes.io/part-of: troubleshooting-backend-app
spec:
  lookupPolicy:
    local: false
  tags:
    - name: latest
      annotations:
        openshift.io/generated-by: OpenShiftWebConsole
        openshift.io/imported-from: 'quay.io/mathianasj/troubleshooting-frontend:latest'
      from:
        kind: DockerImage
        name: 'quay.io/mathianasj/troubleshooting-frontend:latest'
      referencePolicy:
        type: Local
