kind: Deployment
apiVersion: apps/v1
metadata:
  annotations:
    alpha.image.policy.openshift.io/resolve-names: '*'
    app.openshift.io/connects-to: >-
      [{"apiVersion":"apps.openshift.io/v1","kind":"DeploymentConfig","name":"postgresql"}]
    app.openshift.io/route-disabled: 'false'
    image.openshift.io/triggers: >-
      [{"from":{"kind":"ImageStreamTag","name":"troubleshooting-backend:latest","namespace":"{{ .Release.namespace }}"},"fieldPath":"spec.template.spec.containers[?(@.name==\"troubleshooting-backend\")].image","pause":"false"}]
  name: troubleshooting-backend
  labels:
    app: troubleshooting-backend
    app.kubernetes.io/component: troubleshooting-backend
    app.kubernetes.io/instance: troubleshooting-backend
    app.kubernetes.io/name: troubleshooting-backend
    app.kubernetes.io/part-of: troubleshooting-backend-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: troubleshooting-backend
  template:
    metadata:
      labels:
        app: troubleshooting-backend
        deployment: troubleshooting-backend
    spec:
      containers:
        - name: troubleshooting-backend
          image: >-
            image-registry.openshift-image-registry.svc:5000/troubleshooting/troubleshooting-backend@sha256:c7d4363662a9d802de61c2e5038510a960e9863fab902de8c407af4e886f1a2f
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 8443
              protocol: TCP
          resources: {}
          readinessProbe:
            httpGet:
              path: /q/health/ready
              port: 8080
              scheme: HTTP
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
---
kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: troubleshooting-backend
  labels:
    app: troubleshooting-backend
    app.kubernetes.io/component: troubleshooting-backend
    app.kubernetes.io/instance: troubleshooting-backend
    app.kubernetes.io/name: troubleshooting-backend
    app.kubernetes.io/part-of: troubleshooting-backend-app
spec:
  lookupPolicy:
    local: false
  tags:
    - name: latest
      annotations:
        openshift.io/imported-from: 'quay.io/mathianasj/troubleshooting-backend:latest'
      from:
        kind: DockerImage
        name: 'quay.io/mathianasj/troubleshooting-backend:latest'
      importPolicy:
        importMode: Legacy
      referencePolicy:
        type: Local
